workflows:
  ios-build:
    name: Godot iOS Signed Build
    max_build_duration: 120

    environment:
      xcode: 16.3

    scripts:
      - name: Select Xcode
        script: sudo xcode-select -s /Applications/Xcode.app

      - name: Find project
        script: |
          cd ios
          XCODEPROJ=$(find . -name "*.xcodeproj" | head -n 1)
          echo "Project: $XCODEPROJ"

          SCHEME=$(basename "$XCODEPROJ" .xcodeproj)
          echo "Scheme: $SCHEME"

          echo "export XCODEPROJ=$XCODEPROJ" >> $CM_ENV
          echo "export SCHEME=$SCHEME" >> $CM_ENV

      - name: Clean build
        script: |
          xcodebuild clean \
            -project "$XCODEPROJ" \
            -scheme "$SCHEME"

      - name: Archive iOS app
        script: |
          xcodebuild \
            -project "$XCODEPROJ" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -allowProvisioningUpdates \
            clean archive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive

      - name: Create ExportOptions.plist
        script: |
          cat > $CM_BUILD_DIR/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>

              <key>signingStyle</key>
              <string>automatic</string>

              <key>teamID</key>
              <string>9WY9B7WP2D</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportOptionsPlist $CM_BUILD_DIR/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ipa

    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive